# Generated by Django 2.2.6 on 2019-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20191013_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollresult',
            name='method_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='ranked_choices',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='voteline',
            constraint=models.UniqueConstraint(fields=('vote', 'rank'), name='unique_ranks_per_vote'),
        ),
        migrations.AddConstraint(
            model_name='voteline',
            constraint=models.UniqueConstraint(fields=('vote', 'candidate'), name='unique_candidates_per_vote'),
        ),
    ]
